# config-example.yaml
# This file defines storage locations and any
# front-page "readme" material in markdown
# ------------------------------------------------

# --- STORAGE ----------------------
# **Local/network mounts only: no http URLs here**
# Each key defines a starting point in the local filesystem.
# (if no config is found, the current working folder is shared)
storage:
  data:
    path: '/Users/billy/data'
    description: 'Local data on my laptop'
  vsp-public:
    path: '/Users/billy/public-svn'
    description: 'VSP/TU-Berlin public datasets'

# --- FRONT-PAGE TEXT -------------
# Readme can either be a .md markdown filename,
# or you can put markdown text directly in this file with "readme: |"
#
tagline: 'Transport simulation data visualizer'
# readme: 'readme.md'
# # or
# readme: |
#   Welcome to My SimWrapper
#   ========================
#   Markdown text here
#   - notes 1
#   - notes 2

